services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ${SETTING_PATH}/jellyfin/config:/config
      - ${SETTING_PATH}/jellyfin/cache:/cache
      - ${CONTENT_PATH}/movies:/movies
      - ${CONTENT_PATH}/tv:/tv
    restart: 'unless-stopped'

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${SETTING_PATH}/transmission:/config
      - ${CONTENT_PATH}/downloads/complete:/downloads/complete
      - ${CONTENT_PATH}/downloads/complete/tv-sonarr:/downloads/complete/tv-sonarr
      - ${CONTENT_PATH}/downloads/complete/radarr:/downloads/complete/radarr
      - ${CONTENT_PATH}/downloads/incomplete:/downloads/incomplete
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${SETTING_PATH}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${SETTING_PATH}/radarr:/config
      - ${CONTENT_PATH}/movies:/movies
      - ${CONTENT_PATH}/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${SETTING_PATH}/sonarr:/config
      - ${CONTENT_PATH}/tv:/tv
      - ${CONTENT_PATH}/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped